const mongoose = require('mongoose');

const bookingSchema = new mongoose.Schema({
    show:{
        type:mongoose.Schema.Types.ObjectId,
        ref:'shows_user',
        required: true
    },
    user:{
        type:mongoose.Schema.Types.ObjectId,
        ref:'user',
        required:false
    },
    seats:{
        type:Array,
        required:true
    },
    // Keep transactionId for the final payment ID (e.g., Razorpay payment_id)
    transactionId:{
        type:String,
        required:false, // Not required initially, populated after successful payment
    },
    totalAmount:{
        type:Number,
        required:true,
    },
    // --- ADD THESE NEW FIELDS ---
    status: {
        type: String,
        enum: ['pending', 'confirmed', 'failed', 'cancelled'],
        default: 'pending', // Default to pending until payment is verified
        required: true
    },
    razorpayOrderId: { // To store the order ID generated by Razorpay
        type: String,
        required: false, // Required if using Razorpay, but optional for schema definition
    },
    // ----------------------------
    bookedAt: {
        type: Date,
        default: Date.now
    }
}, {
    timestamps: true
});

const bookingModel = mongoose.model('bookings_user', bookingSchema);
module.exports = bookingModel;